Use LAST_RECORDED_GUID to speed-up CF acceptance test

diff --git a/etc/concourse/scripts/cf-acceptance-test b/etc/concourse/scripts/cf-acceptance-test
--- a/etc/concourse/scripts/cf-acceptance-test
+++ b/etc/concourse/scripts/cf-acceptance-test
@@ -17,14 +17,27 @@ echo "Logging to CF ..."
 
 if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
   skip='--skip-ssl-validation'
+  insecure='--insecure'
 fi
 
 cf api https://api.$CF_SYS_DOMAIN $skip
 cf login -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
 
+# Find params to speed-up bridge processing
 export ORG_GUID=$(cf org $CF_ORG --guid)
+echo "Org GUID: $ORG_GUID"
 
-echo "Runnining custom configuration ..."
+TOKEN=$(curl $insecure --user $CC_CLIENT_ID:$CC_CLIENT_SECRET -s "https://uaa.$CF_SYS_DOMAIN/oauth/token?grant_type=client_credentials" | jq -r .access_token)
+if [ "$TOKEN" == "null" -o -z "$TOKEN" ]; then
+  echo "Cannot obtain token for access to CF API !"
+  exit 1
+fi
+EVENTS_URL="https://api.$CF_SYS_DOMAIN/v2/app_usage_events"
+NUM_EVENTS=$(curl -s $insecure -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" "$EVENTS_URL?results-per-page=1" | jq '.total_results')
+export LAST_RECORDED_GUID=$(curl -s $insecure -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" "$EVENTS_URL?results-per-page=1&page=$NUM_EVENTS" | jq '.resources[0].metadata.guid')
+echo "Last recorded GUID: $LAST_RECORDED_GUID"
+
+echo "Replacing ORG_GUID and LAST_RECORDED_GUID in bridge manifest ..."
 abacus_config_dir=$ABACUS_CONFIG_DIR
 abacus_dir=$ABACUS_PROJECT_DIR
 $abacus_dir/etc/concourse/scripts/configure $abacus_config_dir
@@ -50,7 +63,9 @@ pushd $abacus_dir
   restartAppsWithRetry
 
   echo "Starting Acceptance test ..."
-  npm run acceptance -- --organization-guid=$ORG_GUID \
+  npm run acceptance -- --reporting-app=$REPORTING_APP \
+  --cf-domain=$CF_DOMAIN \
+  --organization-guid=$ORG_GUID \
   --total-timeout=$CI_PIPELINE_TIMEOUT \
   --start-timeout=$CI_START_TIMEOUT
 
