Improvements in concourse deployment scripts
- create or update UAA clients
- db service instance deletion

Signed-off-by: Hristo Dobtchev <hristo.dobtchev@sap.com>

diff --git a/etc/concourse/scripts/cf-deploy-infra b/etc/concourse/scripts/cf-deploy-infra
--- a/etc/concourse/scripts/cf-deploy-infra
+++ b/etc/concourse/scripts/cf-deploy-infra
@@ -82,27 +82,24 @@ if [ $abacus_login = 0 ]; then
   unmapRoutes abacus-usage-reporting 6
 fi
 
+if [ $abacus_login = 0 ]; then
+  echo "Waiting for db service instance deletion ..."
+  service_deletion_status=$(cf service db)
+  until grep -q "Service instance db not found" <<< "$service_deletion_status"
+  do
+    if grep -q 'status code: 409' <<< $service_deletion_status ; then
+      echo "DB deletion failed!"
+      exit 1
+    fi
+    sleep 3s
+    service_deletion_status=$(cf service db)
+  done
+  echo "Done."
+fi
 #
 # Enable error checks
 #
 set -e
-
-if [ $abacus_login = 0 ]; then
-  echo "Waiting for db service instance deletion ..."
-  until cf service db | grep -q "Service instance db not found\|status code: 409"
-  do
-    sleep 3s
-  done
-  echo "Done."
-  service_deletion_status=$(cf service db)
-  cf service db
-  if grep -q 'Service instance db not found' <<< $service_deletion_status ; then
-    echo "DB deletion finished successfully."
-  else
-    echo "DB deletion failed!"
-    exit 1
-  fi
-fi
 
 echo "Logging to $CF_API as admin ..."
 cf api $skip "https://api.$CF_API"
@@ -149,8 +146,6 @@ if [ "$CREATE_DB_SERVICE" == "true" ]; then
 else
   echo "Using DB URL provided in abacus-config !"
 fi
-
-$SCRIPT_DIR/create-uaa-clients
 
 if [ "$PURGE_APP_USAGE_EVENTS" == "true" ]; then
   echo "Purging app-usage events ..."
diff --git a/etc/concourse/scripts/create-uaa-clients b/etc/concourse/scripts/create-uaa-clients
--- a/etc/concourse/scripts/create-uaa-clients
+++ b/etc/concourse/scripts/create-uaa-clients
@@ -2,29 +2,48 @@
 
 set -e -x
 
+function create_or_update_client() {
+   client_id="$1"
+   secret="$2"
+   shift 2
+   uaac_parameters="$@"
+
+   echo "Checking if UAA client \"$client_id\" exists ..."
+   set +e
+   uaac client get "$client_id"
+   client_found=$?
+   set -e
+
+   if [[ "$client_found" != 0 ]]; then
+     echo "Creating new UAA client \"$client_id\""
+     uaac client add "$client_id" --secret "$secret" ${uaac_parameters}
+   else
+     echo "Updating existing UAA client \"$client_id\""
+     set +e
+     update_result=$(uaac client update "$client_id" ${uaac_parameters})
+     set -e
+     if [[ "$?" != 0 ]] && [[ "$update_result" != "Nothing to update*" ]]; then
+       echo "Failed to update UAA client due to $update_result"
+       exit 1
+     fi
+     uaac secret set "$client_id" --secret "$secret"
+   fi
+}
+
 echo "Logging to UAA ..."
 if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
   skip='--skip-ssl-validation'
 fi
+
 uaac target "uaa.$CF_API" $skip
 uaac token client get "$UAA_ADMIN" -s "$UAA_SECRET"
 
-echo "Trying to delete existing UAA clients ..."
-set +e
-uaac client delete "$SYSTEM_CLIENT_ID"
-uaac client delete "$CC_CLIENT_ID"
-uaac client delete "$BRIDGE_CLIENT_ID"
-uaac client delete "$CONTAINER_CLIENT_ID"
-uaac client delete "$OBJECT_STORAGE_CLIENT_ID"
-uaac client delete "$HYSTRIX_CLIENT_ID"
-set -e
-
 echo "Creating UAA clients ..."
-uaac client add "$SYSTEM_CLIENT_ID" --authorized_grant_types client_credentials --authorities abacus.usage.write,abacus.usage.read --scope abacus.usage.write,abacus.usage.read --secret "$SYSTEM_CLIENT_SECRET"
+create_or_update_client "$SYSTEM_CLIENT_ID" "$SYSTEM_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities abacus.usage.write,abacus.usage.read --scope abacus.usage.write,abacus.usage.read
 if [ "$PURGE_APP_USAGE_EVENTS" == "true" ]; then
-  uaac client add "$CC_CLIENT_ID" --authorized_grant_types client_credentials --authorities cloud_controller.admin --secret "$CC_CLIENT_SECRET"
+  create_or_update_client "$CC_CLIENT_ID" "$CC_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities cloud_controller.admin
 fi
-uaac client add "$BRIDGE_CLIENT_ID" --authorized_grant_types client_credentials --authorities "$BRIDGE_CLIENT_AUTHORITIES" --secret "$BRIDGE_CLIENT_SECRET"
-uaac client add "$CONTAINER_CLIENT_ID" --authorized_grant_types client_credentials --authorities abacus.usage.linux-container.write,abacus.usage.linux-container.read --scope abacus.usage.linux-container.write,abacus.usage.linux-container.read --secret "$CONTAINER_CLIENT_SECRET"
-uaac client add "$OBJECT_STORAGE_CLIENT_ID" --authorized_grant_types client_credentials --authorities abacus.usage.object-storage.write,abacus.usage.object-storage.read --scope abacus.usage.object-storage.write,abacus.usage.object-storage.read --secret "$OBJECT_STORAGE_CLIENT_SECRET"
-uaac client add "$HYSTRIX_CLIENT_ID" --authorized_grant_types client_credentials --authorities abacus.system.read --scope abacus.system.read --secret "$HYSTRIX_CLIENT_SECRET"
+create_or_update_client "$BRIDGE_CLIENT_ID" "$BRIDGE_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities "$BRIDGE_CLIENT_AUTHORITIES"
+create_or_update_client "$CONTAINER_CLIENT_ID"  "$CONTAINER_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities abacus.usage.linux-container.write,abacus.usage.linux-container.read --scope abacus.usage.linux-container.write,abacus.usage.linux-container.read
+create_or_update_client "$OBJECT_STORAGE_CLIENT_ID" "$OBJECT_STORAGE_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities abacus.usage.object-storage.write,abacus.usage.object-storage.read --scope abacus.usage.object-storage.write,abacus.usage.object-storage.read
+create_or_update_client "$HYSTRIX_CLIENT_ID" "$HYSTRIX_CLIENT_SECRET" --authorized_grant_types client_credentials --authorities abacus.system.read --scope abacus.system.read
