Pipeline should not delete db and sec groups if existing (#510)
Signed-off-by: Nikolay Maslarski <nikolay.maslarski@sap.com>

diff --git a/etc/concourse/scripts/cf-deploy-infra b/etc/concourse/scripts/cf-deploy-infra
--- a/etc/concourse/scripts/cf-deploy-infra
+++ b/etc/concourse/scripts/cf-deploy-infra
@@ -10,85 +10,10 @@ env | sort
 SCRIPT_DIR="${BASH_SOURCE%/*}"
 source $SCRIPT_DIR/common-functions
 
-function unmapRoutes {
-  if [ -z "$1" ]; then
-     echo "Cannot map app without a name !"
-     exit 1
-  fi
-  if [ -z "$2" ]; then
-    echo "Unknown number of instances !"
-    exit 1
-  fi
-
-  local APP_NAME=$1
-  local INSTANCES=$(expr $2 - 1)
-
-  echo "Unmapping $2 (0-$INSTANCES) instances of $APP_NAME in $CF_DOMAIN domain ..."
-  for i in `seq 0 $INSTANCES`;
-  do
-    cf unmap-route "$APP_NAME-$i" $CF_DOMAIN --hostname "$APP_NAME"
-  done
-}
-
 #
 # Get platform info
 #
 unamestr=`uname`
-
-#
-# Disable error checks
-#
-set +e
-
-echo "Logging to $CF_ORG/$CF_SPACE @ $CF_API ..."
-if [ "$SKIP_SSL_VALIDATION" == "true" ]; then
-  skip='--skip-ssl-validation'
-  k='-k'
-fi
-cf login -a https://api.$CF_API $skip -u $CF_ADMIN_USER -p $CF_ADMIN_PASSWORD -o $CF_ORG -s $CF_SPACE
-
-abacus_login=$?
-
-if [ $abacus_login = 0 ]; then
-  echo "Cleaning up $CF_ORG/$CF_SPACE ..."
-  getApps
-
-  if [ "$CREATE_DB_SERVICE" == "true" ]; then
-    echo "Unbinding service instance db ..."
-    if [[ "$unamestr" == 'Linux' ]]; then
-      echo ${APPS[@]} | xargs -n1 | xargs -P 5 -i cf unbind-service {} db
-    else
-      echo ${APPS[@]} | xargs -n1 | xargs -P 5 -n 1 -J {} cf unbind-service {} db
-    fi
-
-    echo "Deleting service instance db ..."
-    cf delete-service -f db
-
-    echo "Waiting for db service instance deletion ..."
-    service_deletion_status=$(cf service db)
-    until grep -q "Service instance db not found" <<< "$service_deletion_status"
-    do
-      if grep -q 'status code: 409' <<< $service_deletion_status ; then
-        echo "DB deletion failed!"
-        exit 1
-      fi
-      sleep 3s
-      service_deletion_status=$(cf service db)
-    done
-    echo "Done."
-  else
-    echo "Using DB URL provided in abacus-config !"
-  fi
-
-  echo "Unmapping routes ..."
-  unmapRoutes abacus-usage-collector 6
-  unmapRoutes abacus-usage-reporting 6
-fi
-
-#
-# Enable error checks
-#
-set -e
 
 echo "Logging to $CF_API as admin ..."
 cf api $skip "https://api.$CF_API"
@@ -96,15 +21,12 @@ cf api $skip "https://api.$CF_API"
 echo "" | cf login -u "$CF_ADMIN_USER" -p "$CF_ADMIN_PASSWORD"
 
 echo "Recreating organization and space ..."
-cf delete-org -f "$CF_ORG"
-cf delete-quota -f "$CF_ORG"
 cf create-quota "$CF_ORG" -m 80g -i 4g -r 80 -s 2 --allow-paid-service-plans
 cf create-org "$CF_ORG" -q "$CF_ORG"
 cf create-space "$CF_SPACE" -o "$CF_ORG"
 cf enable-service-access "$DB_SERVICE_NAME" -p "$DB_PLAN_NAME" -o "$CF_ORG"
 
 echo "Recreating user ..."
-cf delete-user -f "$CF_USER"
 cf create-user "$CF_USER" "$CF_PASSWORD"
 cf set-org-role "$CF_USER" "$CF_ORG" OrgManager
 cf set-space-role "$CF_USER" "$CF_ORG" "$CF_SPACE" SpaceManager
@@ -120,16 +42,29 @@ cf login -a "https://api.$CF_API" -u "$CF_USER" -p "$CF_PASSWORD" -o "$CF_ORG" -
 if [ "$CREATE_DB_SERVICE" == "true" ]; then
   echo "Creating new DB service instance ..."
   cf create-service "$DB_SERVICE_NAME" "$DB_PLAN_NAME" db
-  until cf service db | grep -q 'Status: create succeeded\|Status: create failed\|Service instance .* not found'
+  until cf service db | grep -q 'Status: \(create\|update\) succeeded\|Status: \(create\|update\) failed\|Service instance .* not found'
   do
     sleep 3s
   done
   service_creation_status=$(cf service db)
-  cf service db
-  if grep -q 'Status: create succeeded' <<< $service_creation_status ; then
+  if grep -q 'Status: \(create\|update\) succeeded' <<< $service_creation_status ; then
     echo "DB creation finished successfully."
   else
     echo "DB creation failed!"
+    exit 1
+  fi
+
+  echo "Updating DB service instance ..."
+  cf update-service db -p "$DB_PLAN_NAME"
+  until cf service db | grep -q 'Status: \(create\|update\) succeeded\|Status: \(create\|update\) failed\|Service instance .* not found'
+  do
+    sleep 3s
+  done
+  service_creation_status=$(cf service db)
+  if grep -q 'Status: \(create\|update\) succeeded' <<< $service_creation_status ; then
+    echo "DB update finished successfully."
+  else
+    echo "DB update failed!"
     exit 1
   fi
 else
