Configure unbind and db delete in pipeline
Signed-off-by: Nikolay Maslarski <nikolay.maslarski@sap.com>

diff --git a/etc/concourse/scripts/cf-deploy-infra b/etc/concourse/scripts/cf-deploy-infra
--- a/etc/concourse/scripts/cf-deploy-infra
+++ b/etc/concourse/scripts/cf-deploy-infra
@@ -53,16 +53,29 @@ if [ $abacus_login = 0 ]; then
   echo "Cleaning up $CF_ORG/$CF_SPACE ..."
   getApps
 
-  echo "Unbinding service instance db ..."
-  if [[ "$unamestr" == 'Linux' ]]; then
-    echo ${APPS[@]} | xargs -n1 | xargs -P 5 -i cf unbind-service {} db
-  else
-    echo ${APPS[@]} | xargs -n1 | xargs -P 5 -n 1 -J {} cf unbind-service {} db
-  fi
-
   if [ "$CREATE_DB_SERVICE" == "true" ]; then
+    echo "Unbinding service instance db ..."
+    if [[ "$unamestr" == 'Linux' ]]; then
+      echo ${APPS[@]} | xargs -n1 | xargs -P 5 -i cf unbind-service {} db
+    else
+      echo ${APPS[@]} | xargs -n1 | xargs -P 5 -n 1 -J {} cf unbind-service {} db
+    fi
+
     echo "Deleting service instance db ..."
     cf delete-service -f db
+
+    echo "Waiting for db service instance deletion ..."
+    service_deletion_status=$(cf service db)
+    until grep -q "Service instance db not found" <<< "$service_deletion_status"
+    do
+      if grep -q 'status code: 409' <<< $service_deletion_status ; then
+        echo "DB deletion failed!"
+        exit 1
+      fi
+      sleep 3s
+      service_deletion_status=$(cf service db)
+    done
+    echo "Done."
   else
     echo "Using DB URL provided in abacus-config !"
   fi
@@ -72,20 +85,6 @@ if [ $abacus_login = 0 ]; then
   unmapRoutes abacus-usage-reporting 6
 fi
 
-if [ $abacus_login = 0 ]; then
-  echo "Waiting for db service instance deletion ..."
-  service_deletion_status=$(cf service db)
-  until grep -q "Service instance db not found" <<< "$service_deletion_status"
-  do
-    if grep -q 'status code: 409' <<< $service_deletion_status ; then
-      echo "DB deletion failed!"
-      exit 1
-    fi
-    sleep 3s
-    service_deletion_status=$(cf service db)
-  done
-  echo "Done."
-fi
 #
 # Enable error checks
 #
